<?php
/**
 * @file
 * Code for the Thing feature.
 */

include_once 'thing.features.inc';

function thing_menu() {
  $items = array();
  $items['api/thing'] = array(
    'page callback' => 'thing_endpoint',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  return $items;
}

function thing_endpoint() {
  // @todo define and check permission of save_thing_data
  $uid = user_authenticate($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']);
  if ($uid !== false) {
    $data = json_decode(file_get_contents("php://input"), true);
    $query = " 
      SELECT node.created AS node_created, node.nid AS nid
      FROM 
      {node} node
      LEFT JOIN {field_data_field_thing_id} field_data_field_thing_id ON node.nid = field_data_field_thing_id.entity_id AND (field_data_field_thing_id.entity_type = 'node' AND field_data_field_thing_id.deleted = '0')
      WHERE (( (node.status = '1') AND (node.type IN  ('thing')) AND (field_data_field_thing_id.field_thing_id_value='" . $data['id'] . "') ))
    ";
    //$results = db_query($query, array("id" => $data['id']));
    $results = db_query($query);
    $arr = array();
    foreach ($results as $results) {
      array_push($arr, $results);
    }
    if (count($arr) > 0) {
      // record the data
      $id = $data['id'];
      unset($data['id']);
      thing_save_packet($id, $data);
    }
    else {
      // create the thing and its table
      $id = $data['id'];
      unset($data['id']);
      $schema = array(
        'fields' => array(
          'id' => array('type' => 'serial', 'unsigned' => TRUE, 'not null' => TRUE)
        ),
        'primary key' => array('id')
      );
      foreach($data as $key => $value) {
        $schema['fields'][$key] = array('type' => 'varchar', 'length' => 256);
      } 
      db_create_table('thing_' . $id, $schema);
        
      $node = new stdClass();
      $node->type = 'thing';
      $node->title = $id;
      node_object_prepare($node);
      $node->language = LANGUAGE_NONE;
      $node->uid = $uid;
      $node->status = 1;
      $node->promote = 0; //(1 or 0): promoted to front page
      $node->comment = 1; // 0 = comments disabled, 1 = read only, 2 = read/write
      $node->field_thing_id[$node->language][]['value'] = $id;
      $node = node_submit($node); // Prepare node for saving
      node_save($node);
    }
  }
}

function thing_save_packet($id, $data) {
  db_insert('thing_' . $id)->fields($data)->execute();
}




